### ISSUE TITLE
Creación de cuenta

### ISSUE THREAD

**Issue by David-sqrtpi** [David-sqrtpi/CSW-java#3]
La creación de cuenta funciona, falta validar el formulario y las pruebas.

**Comment by willyam11** [comment]
creación de  las validaciones pero hay un error en los nombres que tienen los atributos

**Comment by willyam11** [comment]
creación de  las validaciones hecha faltan pruebas =)

**Comment by David-sqrtpi** [comment]
http://localhost:4200/crear-cuenta
Validación del botón terminada. Faltan las pruebas con los nuevos cambios

**Comment by willyam11** [comment]
pruebas para el caso de crear-cuentas terminadas
